---
- name: Create Client Username "{{ cu.client_username_name }}"
  uri:
   url: "http://{{ mgmt_ip }}:{{ port }}/SEMP/v2/config/msgVpns/{{ vpn }}/clientUsernames"
   method: POST
   user: "{{ semp_username }}"
   password: "{{ semp_password }}"
   headers:
    Content-Type: "application/json"
   body:
    clientUsername: "{{ cu.client_username_name }}"
    aclProfileName: "{{ cu.acl_profile_name }}"
    clientProfileName: "{{ cu.client_profile_name }}"
    enabled: true
    password: "{{ cu.password }}"
   body_format: json
   force_basic_auth: yes
   status_code: 200,400
   return_content: yes
  register: result
  ignore_errors: True
  retries: 3
  delay: 10

- name: List Success for Username creation
  debug:
    var: result.msg
  when: result.json.meta.responseCode == 200

- name: List Failure for Username creation
  debug:
   var: result.json.meta.error.status
  when: result.json.meta.responseCode != 200
