---
- name: Create Message-vpn "{{ vpn.vpn_name }}"
  uri:
   url: "http://{{ mgmt_host }}:{{ mgmt_port }}/SEMP/v2/config/msgVpns"
   method: POST
   user: "{{ semp_username }}"
   password: "{{ semp_password }}"
   headers:
    Content-Type: "application/json"
   body:
    msgVpnName: "{{ vpn.vpn_name }}"
    authenticationBasicType: "internal"
    enabled: true
    maxConnectionCount: 10
    maxMsgSpoolUsage: 100
    maxSubscriptionCount: 500
    serviceWebPlainTextEnabled: "{{ vpn.serviceWebPlainTextEnabled }}"
   body_format: json
   force_basic_auth: yes
   status_code: 200,400
   return_content: yes
  register: result
  ignore_errors: True
  retries: 0
  delay: 10

- name: Error in VPN Creation?
  debug:
    var: result.json.meta.error.status
  when: result.json.meta.responseCode != 200
