---
- name: Create Client Profile "{{ cp.client_profile_name }}"
  uri:
   url: "http://{{ mgmt_host }}:{{ mgmt_port }}/SEMP/v2/config/msgVpns/{{ vpn }}/clientProfiles"
   method: POST
   user: "{{ semp_username }}"
   password: "{{ semp_password }}"
   headers:
    Content-Type: "application/json"
   body:
    clientProfileName: "{{ cp.client_profile_name }}"
    allowGuaranteedMsgReceiveEnabled: true
    allowGuaranteedMsgSendEnabled: true
   body_format: json
   force_basic_auth: yes
   status_code: 200,400
   return_content: yes
  register: result
  ignore_errors: True
  retries: 0
  delay: 3

- name: Error in Client Profile creation?
  debug:
   var: result.json.meta.error.status
  when: result.json.meta.responseCode != 200
